# Generated by Django 3.2.22 on 2023-11-05 08:02

import authe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=authe.models.uniq_name_upload),
        ),
    ]
